CREATE TABLE IF NOT EXISTS user1(
    id SERIAL PRIMARY KEY ,
    name VARCHAR (50) NOT NULL,
    username VARCHAR (50) NOT NULL UNIQUE ,
    email VARCHAR (50) NOT NULL UNIQUE ,
    password VARCHAR (50) NOT NULL



)